<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Richard Castaneda">

<title>ADTA 5410: Week 7 R Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Week 7 RLab on GAM_files/libs/clipboard/clipboard.min.js"></script>
<script src="Week 7 RLab on GAM_files/libs/quarto-html/quarto.js"></script>
<script src="Week 7 RLab on GAM_files/libs/quarto-html/popper.min.js"></script>
<script src="Week 7 RLab on GAM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Week 7 RLab on GAM_files/libs/quarto-html/anchor.min.js"></script>
<link href="Week 7 RLab on GAM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Week 7 RLab on GAM_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Week 7 RLab on GAM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Week 7 RLab on GAM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Week 7 RLab on GAM_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ADTA 5410: Week 7 R Lab</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Richard Castaneda </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>We will use North Carololina birth records for the year 2004. We want to look at the relation between the habits and practices of expectant mothers and the birth of their children. The dataset is a random sample from the original dataset.</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<p><strong>Predictors</strong></p>
<ul>
<li><p><strong>fage</strong>: father’s age in years.</p></li>
<li><p><strong>mage</strong>: mother’s age in years.</p></li>
<li><p><strong>mature</strong>: maturity status of mother.</p></li>
<li><p><strong>weeks</strong>: length of pregnancy in weeks.</p></li>
<li><p><strong>premie</strong>: whether the birth was classified as premature (premie) or full-term.</p></li>
<li><p><strong>visits</strong>: number of hospital visits during pregnancy.</p></li>
<li><p><strong>marital</strong>: whether mother is married or not married at birth.</p></li>
<li><p><strong>gained</strong>: weight gained by mother during pregnancy in pounds.</p></li>
<li><p><strong>gender</strong>: gender of the baby, female or male.</p></li>
<li><p><strong>habit</strong>: status of the mother as a nonsmoker or a smoker.</p></li>
<li><p><strong>whitemom</strong>: whether mother is white or not white.</p></li>
</ul>
</section>
<section id="outcome-variables" class="level1">
<h1><strong>Outcome variables<a href="https://instructorecdsjwfd.labs.coursera.org/notebooks/source/Week5/Week5_Lab.ipynb#Outcome-variables">¶</a></strong></h1>
<ul>
<li><strong>weight</strong>: weight of the baby at birth in pounds. (Regression problem)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mgcv' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'nlme' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This is mgcv 1.8-42. For overview type 'help("mgcv-package")'.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data is stored in a csv file, the first row contains the variable names. </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>mydata<span class="ot">&lt;-</span><span class="fu">read.csv</span> (<span class="st">"C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">rcase</span><span class="sc">\\</span><span class="st">Downloads</span><span class="sc">\\</span><span class="st">nc.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># let's print the data structure to have an idea of the data we are dealing with</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>mydata<span class="ot">&lt;-</span>mydata<span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>lowbirthweight)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   999 obs. of  12 variables:
 $ fage    : int  NA NA 19 21 NA NA 18 17 NA 20 ...
 $ mage    : int  13 14 15 15 15 15 15 15 16 16 ...
 $ mature  : chr  "younger mom" "younger mom" "younger mom" "younger mom" ...
 $ weeks   : int  39 42 37 41 39 38 37 35 38 37 ...
 $ premie  : chr  "full term" "full term" "full term" "full term" ...
 $ visits  : int  10 15 11 6 9 19 12 5 9 13 ...
 $ marital : chr  "married" "married" "married" "married" ...
 $ gained  : int  38 20 38 34 27 22 76 15 NA 52 ...
 $ weight  : num  7.63 7.88 6.63 8 6.38 5.38 8.44 4.69 8.81 6.94 ...
 $ gender  : chr  "male" "male" "female" "male" ...
 $ habit   : chr  "nonsmoker" "nonsmoker" "nonsmoker" "nonsmoker" ...
 $ whitemom: chr  "not white" "not white" "white" "white" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Omit NA values</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(mydata)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's also take a look at the data</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(mydata))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fage mage      mature weeks    premie visits marital gained weight gender
3    19   15 younger mom    37 full term     11 married     38   6.63 female
4    21   15 younger mom    41 full term      6 married     34   8.00   male
7    18   15 younger mom    37 full term     12 married     76   8.44   male
8    17   15 younger mom    35    premie      5 married     15   4.69   male
10   20   16 younger mom    37 full term     13 married     52   6.94 female
11   30   16 younger mom    45 full term      9 married     28   7.44   male
       habit  whitemom
3  nonsmoker     white
4  nonsmoker     white
7  nonsmoker not white
8  nonsmoker not white
10 nonsmoker     white
11 nonsmoker     white</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the summary statistics </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(mydata))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      fage            mage          mature              weeks      
 Min.   :14.00   Min.   :15.00   Length:800         Min.   :20.00  
 1st Qu.:25.00   1st Qu.:22.00   Class :character   1st Qu.:38.00  
 Median :30.00   Median :28.00   Mode  :character   Median :39.00  
 Mean   :30.24   Mean   :27.61                      Mean   :38.47  
 3rd Qu.:35.00   3rd Qu.:33.00                      3rd Qu.:40.00  
 Max.   :55.00   Max.   :50.00                      Max.   :45.00  
    premie              visits        marital              gained     
 Length:800         Min.   : 0.00   Length:800         Min.   : 0.00  
 Class :character   1st Qu.:10.00   Class :character   1st Qu.:21.75  
 Mode  :character   Median :12.00   Mode  :character   Median :30.00  
                    Mean   :12.44                      Mean   :30.77  
                    3rd Qu.:15.00                      3rd Qu.:39.00  
                    Max.   :30.00                      Max.   :85.00  
     weight          gender             habit             whitemom        
 Min.   : 1.000   Length:800         Length:800         Length:800        
 1st Qu.: 6.545   Class :character   Class :character   Class :character  
 Median : 7.380   Mode  :character   Mode  :character   Mode  :character  
 Mean   : 7.209                                                           
 3rd Qu.: 8.130                                                           
 Max.   :11.630                                                           </code></pre>
</div>
</div>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<p>Data Split</p>
<p>Before conducting our analysis, we will split our data into two, one for training and one for testing. In this lab assignment, use the <strong>sample</strong> function in <strong>rsample</strong> package to split your data by using the following seed: <strong>set.seed(1234)</strong></p>
</section>
</section>
<section id="task-1" class="level1">
<h1><strong>Task 1:</strong></h1>
<p>Bu using the <strong>sample</strong> function in R, split <strong>mydata</strong> into training and test sets by putting 70% of the data in training. Use set.seed(1234) when you do the split. Name the training set as <strong>train_data</strong> and the test set as <strong>test_data</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and test sets</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(mydata)), <span class="at">size =</span> <span class="fl">0.7</span> <span class="sc">*</span> <span class="fu">nrow</span>(mydata))</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> mydata[split, ]</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> mydata[<span class="sc">-</span>split, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-2" class="level2">
<h2 class="anchored" data-anchor-id="task-2">Task 2:</h2>
<p>In this task, you will be using the <strong><code>train_data</code></strong> dataset to run a linear regression that takes ‘weight’ as the dependent variable and all the other columns as the predictor.</p>
<ul>
<li><p>You will use the <strong><code>lm()</code></strong> function to estimate your linear model and name it as <strong><code>linearmodel</code></strong>.</p></li>
<li><p>Use the <strong><code>predict()</code></strong> function to predict the ‘weight’ variable in the <strong><code>test_data</code></strong> dataset using <strong><code>linearmodel</code></strong>.</p></li>
<li><p>Store the resulting predictions in a new object called <strong><code>predicted_weights</code></strong>.</p></li>
<li><p>Calculate the mean squared prediction error in the <strong><code>test_data</code></strong> dataset by comparing the predicted ‘weight’ values with the actual ‘weight’ values. Store the resulting value in an object called <strong><code>MSPE_linear</code></strong>.</p></li>
<li><p>Print the value of <strong><code>MSPE_linear</code></strong> to the console using the <strong><code>print()</code></strong> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear regression model on train_data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>linearmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># predict weight using linearmodel</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>predicted_weights <span class="ot">&lt;-</span> <span class="fu">predict</span>(linearmodel, <span class="at">newdata =</span> test_data)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean squared prediction error</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>MSPE_linear <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_data<span class="sc">$</span>weight <span class="sc">-</span> predicted_weights)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MSPE_linear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.032627</code></pre>
</div>
</div>
<h2 id="section-2" class="anchored"></h2>
<p>Task3</p></li>
<li><p>Use the generalized additive model (GAM) function in the <strong><code>mgcv</code></strong> package to complete the same task. In other words, fit a GAM on the <code>train_data</code> using the <strong><code>gam()</code></strong> function. Use the <strong><code>s()</code></strong> function for each predictor. By doing so, you specify that each predictor variable is modeled using a smoothing spline. Save your R object as <code>gam_model</code></p></li>
<li><p>Use the <strong><code>predict()</code></strong> function to predict the ‘weight’ variable in the <strong><code>test_data</code></strong> dataset using <strong><code>gam_model</code></strong>. Store the resulting predictions in a new object called <strong><code>predicted_weights</code></strong>.</p></li>
<li><p>Calculate the mean squared prediction error in the <strong><code>test_data</code></strong> dataset by comparing the predicted ‘weight’ values with the actual ‘weight’ values. Store the resulting value in an object called <strong><code>MSPE_gam</code></strong>.</p></li>
</ul>
<p>Print the value of <strong><code>MSPE_gam</code></strong> to the console using the <strong><code>print()</code></strong> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit GAM model on train_data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>gam_model <span class="ot">&lt;-</span> <span class="fu">gam</span>(weight <span class="sc">~</span> <span class="fu">s</span>(fage) <span class="sc">+</span> <span class="fu">s</span>(mage) <span class="sc">+</span> mature <span class="sc">+</span> <span class="fu">s</span>(weeks) <span class="sc">+</span> premie <span class="sc">+</span> <span class="fu">s</span>(visits) <span class="sc">+</span> marital <span class="sc">+</span> <span class="fu">s</span>(gained) <span class="sc">+</span> gender <span class="sc">+</span> habit <span class="sc">+</span> whitemom, <span class="at">data =</span> train_data)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># predict weight using gam_model</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>predicted_weights <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean squared prediction error</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>MSPE_gam <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_data<span class="sc">$</span>weight <span class="sc">-</span> predicted_weights)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print MSPE_gam</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MSPE_gam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9667269</code></pre>
</div>
</div>
</section>
<section id="task-4" class="level2">
<h2 class="anchored" data-anchor-id="task-4">Task 4</h2>
<ul>
<li>Compare the mean squared prediction error obtained from the linear regression model (<strong><code>linearmodel</code></strong>) in Task 2 and the generalized additive model (<strong><code>gam_model</code></strong>) in the previous task. You will use the <strong><code>MSPE_linear</code></strong> and <strong><code>MSPE_gam</code></strong> values to determine which model performs better in predicting the ‘weight’ variable in the <strong><code>test_data</code></strong> dataset.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean squared prediction error for linear model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>MSPE_linear <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_data<span class="sc">$</span>weight <span class="sc">-</span> <span class="fu">predict</span>(linearmodel, <span class="at">newdata =</span> test_data))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean squared prediction error for GAM model</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>MSPE_gam <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_data<span class="sc">$</span>weight <span class="sc">-</span> <span class="fu">predict</span>(gam_model, <span class="at">newdata =</span> test_data, <span class="at">type =</span> <span class="st">"response"</span>))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MSPE_linear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.032627</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MSPE_gam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9667269</code></pre>
</div>
</div>
<ul>
<li>Comment on your findings.</li>
</ul>
<p>Task 3:</p>
<p>The mean squared prediction error (MSPE) obtained from the linear regression model (MSPE_linear = 1.032627) in Task 2 is higher than the MSPE obtained from the generalized additive model (MSPE_gam = 0.9667269) in the previous task. This indicates that the GAM model performs better than the linear regression model in predicting the ‘weight’ variable in the test_data dataset.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>